// Builds a single, self-contained HTML file for the phoneme Word Search activity.
// Adapted from the original Phoneme_Word_Search.html prototype, restyled to match the
// builder's design system and extended with hover hints mapping phoneme -> English letters.

export function generateWordSearchHtml({ words, phonemeMap, rows, cols, showHints, theme }) {
  const data = {
    words, // [{ display, cleanDisplay, units }]
    map: phonemeMap,
    rows: Number(rows) || 10,
    cols: Number(cols) || 10,
    showHints: !!showHints,
  };

  return `<!DOCTYPE html>
<html lang="en" data-theme="${theme === "dark" ? "dark" : "light"}">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Phoneme Word Search</title>
<style>
  :root {
    --ink: #1E2A32;
    --paper: #F1F5F3;
    --surface: #FFFFFF;
    --primary: #4A5FBF;
    --border: #D7DEDC;
    --highlight: #E3A857;
    --found: #2F6E6B;
  }
  html[data-theme="dark"] {
    --ink: #EAF1EF;
    --paper: #12191C;
    --surface: #1B2428;
    --border: #2B383D;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: "Segoe UI", Inter, system-ui, sans-serif;
    background: var(--paper);
    color: var(--ink);
    padding: 24px 16px 60px;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  h1 { font-size: 1.6rem; margin-bottom: 4px; }
  .sub { opacity: 0.65; margin-bottom: 20px; font-size: 0.95rem; }
  .layout {
    display: flex;
    flex-wrap: wrap;
    gap: 24px;
    justify-content: center;
    align-items: flex-start;
  }
  .grid {
    display: grid;
    background: var(--surface);
    padding: 12px;
    border-radius: 12px;
    border: 1px solid var(--border);
    gap: 3px;
  }
  .cell {
    width: 38px;
    height: 38px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-family: "IBM Plex Mono", monospace;
    font-weight: 600;
    background: var(--paper);
    border: 1px solid var(--border);
    border-radius: 4px;
    cursor: pointer;
    user-select: none;
    font-size: 0.9rem;
  }
  .cell.highlighted { background: var(--highlight) !important; color: #201302; }
  .cell.found { background: var(--found) !important; color: #fff; }

  .word-panel {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 16px;
    min-width: 220px;
  }
  .word-panel h3 { font-size: 1rem; margin-bottom: 10px; }
  .word-item {
    position: relative;
    display: inline-block;
    padding: 6px 10px;
    margin: 4px 4px 0 0;
    background: var(--paper);
    border: 1px solid var(--border);
    border-radius: 6px;
    font-family: "IBM Plex Mono", monospace;
    cursor: help;
  }
  .word-item.found { text-decoration: line-through; opacity: 0.5; }
  .word-item .tip {
    visibility: hidden;
    opacity: 0;
    position: absolute;
    bottom: 115%;
    left: 0;
    background: var(--ink);
    color: var(--paper);
    padding: 4px 8px;
    border-radius: 6px;
    font-size: 0.7rem;
    white-space: nowrap;
    transition: opacity 0.15s ease;
    z-index: 5;
  }
  .word-item:hover .tip { visibility: visible; opacity: 1; }
  footer { margin-top: 24px; font-size: 0.75rem; opacity: 0.55; }
</style>
</head>
<body>
  <h1>Phoneme Word Search</h1>
  <div class="sub">Drag across the grid to find each phoneme word.</div>

  <div class="layout">
    <div class="grid" id="grid"></div>
    <div class="word-panel">
      <h3>Word list</h3>
      <div id="wordList"></div>
    </div>
  </div>

  <footer>Generated by the HCE Phoneme Activity Builder — Speech Pathology classroom tool.</footer>

<script>
  const DATA = ${JSON.stringify(data)};
  const rows = DATA.rows;
  const cols = DATA.cols;

  let gridMatrix = [];
  let isSelecting = false;
  let startCell = null;

  const directions = [
    {dr:0,dc:1},{dr:0,dc:-1},{dr:1,dc:0},{dr:-1,dc:0},
    {dr:1,dc:1},{dr:1,dc:-1},{dr:-1,dc:1},{dr:-1,dc:-1}
  ];

  function build() {
    gridMatrix = Array.from({length: rows}, () => new Array(cols).fill(null));
    let pool = [];
    DATA.words.forEach(w => w.units.forEach(u => { if (!pool.includes(u)) pool.push(u); }));
    if (pool.length === 0) pool = ['æ','b','d','ɪ','p','s','t'];

    DATA.words.forEach(w => {
      let placed = false, attempts = 0;
      while (!placed && attempts < 300) {
        attempts++;
        const d = directions[Math.floor(Math.random()*directions.length)];
        const r = Math.floor(Math.random()*rows);
        const c = Math.floor(Math.random()*cols);
        if (canPlace(w.units, r, c, d)) {
          for (let i = 0; i < w.units.length; i++) {
            gridMatrix[r + d.dr*i][c + d.dc*i] = w.units[i];
          }
          placed = true;
        }
      }
    });

    for (let r = 0; r < rows; r++)
      for (let c = 0; c < cols; c++)
        if (!gridMatrix[r][c]) gridMatrix[r][c] = pool[Math.floor(Math.random()*pool.length)];

    render();
  }

  function canPlace(units, r, c, d) {
    const len = units.length;
    const endR = r + d.dr*(len-1), endC = c + d.dc*(len-1);
    if (endR < 0 || endR >= rows || endC < 0 || endC >= cols) return false;
    for (let i = 0; i < len; i++) {
      const cr = r + d.dr*i, cc = c + d.dc*i;
      if (gridMatrix[cr][cc] && gridMatrix[cr][cc] !== units[i]) return false;
    }
    return true;
  }

  const gridEl = document.getElementById('grid');
  const listEl = document.getElementById('wordList');

  function render() {
    gridEl.innerHTML = '';
    gridEl.style.gridTemplateRows = 'repeat(' + rows + ', 1fr)';
    gridEl.style.gridTemplateColumns = 'repeat(' + cols + ', 1fr)';
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        const cell = document.createElement('div');
        cell.className = 'cell';
        cell.dataset.row = r;
        cell.dataset.col = c;
        cell.textContent = gridMatrix[r][c];
        gridEl.appendChild(cell);
      }
    }
    listEl.innerHTML = '';
    DATA.words.forEach(w => {
      const item = document.createElement('div');
      item.className = 'word-item';
      item.id = 'list-' + w.display;
      item.textContent = w.cleanDisplay;
      if (DATA.showHints) {
        const tip = document.createElement('div');
        tip.className = 'tip';
        tip.textContent = w.units.map(u => (DATA.map[u] ? DATA.map[u].label : u)).join(' ') + ' = "' + w.display + '"';
        item.appendChild(tip);
      }
      listEl.appendChild(item);
    });
  }

  gridEl.addEventListener('mousedown', e => {
    if (!e.target.classList.contains('cell')) return;
    isSelecting = true; startCell = e.target;
    clearHighlights();
    e.target.classList.add('highlighted');
  });
  gridEl.addEventListener('mouseover', e => {
    if (!isSelecting || !e.target.classList.contains('cell')) return;
    clearHighlights();
    highlightPath(startCell, e.target);
  });
  window.addEventListener('mouseup', () => {
    if (!isSelecting) return;
    isSelecting = false;
    checkSelection();
    clearHighlights();
  });

  gridEl.addEventListener('touchstart', e => {
    const t = e.touches[0];
    const cell = document.elementFromPoint(t.clientX, t.clientY);
    if (cell && cell.classList.contains('cell')) {
      isSelecting = true; startCell = cell;
      clearHighlights();
      cell.classList.add('highlighted');
    }
  });
  window.addEventListener('touchmove', e => {
    if (!isSelecting) return;
    const t = e.touches[0];
    const cell = document.elementFromPoint(t.clientX, t.clientY);
    if (cell && cell.classList.contains('cell') && cell.parentNode === gridEl) {
      clearHighlights();
      highlightPath(startCell, cell);
    }
  });
  window.addEventListener('touchend', () => {
    if (!isSelecting) return;
    isSelecting = false;
    checkSelection();
    clearHighlights();
  });

  function getPath(a, b) {
    const r1 = +a.dataset.row, c1 = +a.dataset.col, r2 = +b.dataset.row, c2 = +b.dataset.col;
    const dr = r2 - r1, dc = c2 - c1;
    if (dr === 0 || dc === 0 || Math.abs(dr) === Math.abs(dc)) {
      const steps = Math.max(Math.abs(dr), Math.abs(dc));
      const stepR = dr === 0 ? 0 : dr/steps, stepC = dc === 0 ? 0 : dc/steps;
      const path = [];
      for (let i = 0; i <= steps; i++) path.push({r: r1+stepR*i, c: c1+stepC*i});
      return path;
    }
    return null;
  }
  function highlightPath(a, b) {
    const path = getPath(a, b);
    if (!path) return;
    path.forEach(co => {
      const cell = document.querySelector('[data-row="'+co.r+'"][data-col="'+co.c+'"]');
      if (cell) cell.classList.add('highlighted');
    });
  }
  function clearHighlights() {
    document.querySelectorAll('.cell.highlighted').forEach(c => c.classList.remove('highlighted'));
  }
  function checkSelection() {
    const highlighted = document.querySelectorAll('.cell.highlighted');
    if (highlighted.length === 0) return;
    const cells = Array.from(highlighted);
    const path = getPath(startCell, cells[cells.length-1] || startCell);
    if (!path) return;
    let str1 = '', str2 = '';
    path.forEach(co => str1 += gridMatrix[co.r][co.c]);
    for (let i = path.length-1; i >= 0; i--) str2 += gridMatrix[path[i].r][path[i].c];
    DATA.words.forEach(w => {
      if (!w.found && (w.display === str1 || w.display === str2)) {
        w.found = true;
        path.forEach(co => {
          const cell = document.querySelector('[data-row="'+co.r+'"][data-col="'+co.c+'"]');
          if (cell) cell.classList.add('found');
        });
        const item = document.getElementById('list-' + w.display);
        if (item) item.classList.add('found');
      }
    });
  }

  build();
</script>
</body>
</html>`;
}
