// Builds a single, self-contained HTML file for the phoneme Wordle activity.
// No external JS/CSS dependencies at runtime so it can be opened straight from disk
// (or a school's LMS) with no network connection required.

export function generateWordleHtml({
  targetWord,
  targetPhonemes,
  phonemeMap,
  showHints,
  maxGuesses,
  theme,
}) {
  const data = {
    word: targetWord,
    phonemes: targetPhonemes,
    map: phonemeMap,
    showHints: !!showHints,
    maxGuesses: Number(maxGuesses) || 6,
  };

  return `<!DOCTYPE html>
<html lang="en" data-theme="${theme === "dark" ? "dark" : "light"}">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Phoneme Wordle — ${escapeHtml(targetWord)}</title>
<style>
  :root {
    --ink: #1E2A32;
    --paper: #F1F5F3;
    --surface: #FFFFFF;
    --primary: #2F6E6B;
    --primary-ink: #FFFFFF;
    --accent: #E3A857;
    --border: #D7DEDC;
    --miss: #C9D2D0;
    --present: #E3A857;
    --hit: #2F6E6B;
  }
  html[data-theme="dark"] {
    --ink: #EAF1EF;
    --paper: #12191C;
    --surface: #1B2428;
    --border: #2B383D;
    --miss: #2B383D;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--paper);
    color: var(--ink);
    font-family: "Segoe UI", Inter, system-ui, sans-serif;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 32px 16px 60px;
    min-height: 100vh;
  }
  h1 {
    font-size: 1.6rem;
    margin: 0 0 4px;
    letter-spacing: -0.01em;
  }
  .sub {
    color: var(--ink);
    opacity: 0.65;
    margin-bottom: 24px;
    font-size: 0.95rem;
  }
  .board {
    display: flex;
    flex-direction: column;
    gap: 8px;
    margin-bottom: 28px;
  }
  .row {
    display: flex;
    gap: 8px;
  }
  .cell {
    width: 56px;
    height: 56px;
    border: 2px solid var(--border);
    border-radius: 8px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-family: "IBM Plex Mono", "Courier New", monospace;
    font-size: 1.1rem;
    font-weight: 600;
    background: var(--surface);
    transition: transform 0.15s ease, background 0.2s ease;
  }
  .cell.hit { background: var(--hit); color: #fff; border-color: var(--hit); }
  .cell.present { background: var(--present); color: #201302; border-color: var(--present); }
  .cell.miss { background: var(--miss); border-color: var(--miss); }
  .cell.pop { transform: scale(1.08); }

  .keyboard {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    max-width: 640px;
    justify-content: center;
    margin-bottom: 20px;
  }
  .key {
    position: relative;
    min-width: 46px;
    padding: 10px 8px;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    font-weight: 700;
    font-size: 0.85rem;
    cursor: pointer;
    color: var(--ink);
  }
  .key:hover { border-color: var(--primary); }
  .key .tip {
    visibility: hidden;
    opacity: 0;
    position: absolute;
    bottom: 115%;
    left: 50%;
    transform: translateX(-50%);
    background: var(--ink);
    color: var(--paper);
    padding: 4px 8px;
    border-radius: 6px;
    font-size: 0.7rem;
    font-weight: 400;
    white-space: nowrap;
    transition: opacity 0.15s ease;
    font-family: "IBM Plex Mono", monospace;
  }
  .key:hover .tip { visibility: visible; opacity: 1; }
  .key.used-hit { background: var(--hit); color: #fff; }
  .key.used-present { background: var(--present); }
  .key.used-miss { opacity: 0.4; }
  .key.enter, .key.back { min-width: 70px; background: var(--primary); color: var(--primary-ink); }

  .status {
    min-height: 28px;
    font-weight: 600;
    margin-bottom: 12px;
    text-align: center;
  }
  .status.win { color: var(--hit); }
  .status.lose { color: #b3452f; }
  .hint-line {
    font-size: 0.85rem;
    opacity: 0.75;
    margin-bottom: 18px;
    text-align: center;
    max-width: 460px;
  }
  footer {
    margin-top: 24px;
    font-size: 0.75rem;
    opacity: 0.55;
  }
</style>
</head>
<body>
  <h1>Phoneme Wordle</h1>
  <div class="sub">Guess the word, one phoneme at a time.</div>
  <div class="hint-line" id="hintLine"></div>

  <div class="board" id="board"></div>
  <div class="status" id="status"></div>
  <div class="keyboard" id="keyboard"></div>

  <footer>Generated by the HCE Phoneme Activity Builder — Speech Pathology classroom tool.</footer>

<script>
  const DATA = ${JSON.stringify(data)};

  const board = document.getElementById('board');
  const status = document.getElementById('status');
  const keyboardEl = document.getElementById('keyboard');
  const hintLine = document.getElementById('hintLine');

  const target = DATA.phonemes;
  const wordLen = target.length;
  const maxGuesses = DATA.maxGuesses;

  let currentGuess = [];
  let guessRow = 0;
  let finished = false;

  if (DATA.showHints) {
    hintLine.textContent = 'Hover over each key to see its English letter equivalent.';
  } else {
    hintLine.textContent = 'Hints are turned off for this activity.';
  }

  // Build empty board
  for (let r = 0; r < maxGuesses; r++) {
    const row = document.createElement('div');
    row.className = 'row';
    row.id = 'row-' + r;
    for (let c = 0; c < wordLen; c++) {
      const cell = document.createElement('div');
      cell.className = 'cell';
      cell.id = 'cell-' + r + '-' + c;
      row.appendChild(cell);
    }
    board.appendChild(row);
  }

  // Build keyboard from the phoneme map, shuffled a little for a natural layout
  const keyState = {};
  Object.keys(DATA.map).forEach(ipa => {
    const key = document.createElement('div');
    key.className = 'key';
    key.dataset.ipa = ipa;
    key.textContent = ipa;
    if (DATA.showHints) {
      const tip = document.createElement('div');
      tip.className = 'tip';
      const info = DATA.map[ipa];
      tip.textContent = info.label + ' (as in ' + info.example + ')';
      key.appendChild(tip);
    }
    key.addEventListener('click', () => pressPhoneme(ipa));
    keyboardEl.appendChild(key);
  });

  const enterKey = document.createElement('div');
  enterKey.className = 'key enter';
  enterKey.textContent = 'Enter';
  enterKey.addEventListener('click', submitGuess);
  keyboardEl.appendChild(enterKey);

  const backKey = document.createElement('div');
  backKey.className = 'key back';
  backKey.textContent = 'Back';
  backKey.addEventListener('click', backspace);
  keyboardEl.appendChild(backKey);

  function pressPhoneme(ipa) {
    if (finished) return;
    if (currentGuess.length >= wordLen) return;
    currentGuess.push(ipa);
    renderCurrentRow();
  }

  function backspace() {
    if (finished) return;
    currentGuess.pop();
    renderCurrentRow();
  }

  function renderCurrentRow() {
    for (let c = 0; c < wordLen; c++) {
      const cell = document.getElementById('cell-' + guessRow + '-' + c);
      cell.textContent = currentGuess[c] || '';
    }
  }

  function submitGuess() {
    if (finished) return;
    if (currentGuess.length !== wordLen) {
      status.textContent = 'Not enough phonemes yet.';
      status.className = 'status';
      return;
    }

    const remaining = target.slice();
    const result = new Array(wordLen).fill('miss');

    // First pass: exact matches
    for (let i = 0; i < wordLen; i++) {
      if (currentGuess[i] === target[i]) {
        result[i] = 'hit';
        remaining[i] = null;
      }
    }
    // Second pass: present but wrong position
    for (let i = 0; i < wordLen; i++) {
      if (result[i] === 'hit') continue;
      const idx = remaining.indexOf(currentGuess[i]);
      if (idx !== -1) {
        result[i] = 'present';
        remaining[idx] = null;
      }
    }

    for (let c = 0; c < wordLen; c++) {
      const cell = document.getElementById('cell-' + guessRow + '-' + c);
      cell.classList.add(result[c], 'pop');
      const ipa = currentGuess[c];
      const key = document.querySelector('.key[data-ipa="' + CSS.escape(ipa) + '"]');
      if (key) {
        if (result[c] === 'hit') {
          key.classList.remove('used-present', 'used-miss');
          key.classList.add('used-hit');
        } else if (result[c] === 'present' && !key.classList.contains('used-hit')) {
          key.classList.add('used-present');
        } else if (!key.classList.contains('used-hit') && !key.classList.contains('used-present')) {
          key.classList.add('used-miss');
        }
      }
    }

    const won = result.every(r => r === 'hit');
    if (won) {
      finished = true;
      status.textContent = 'Correct! The word is "' + DATA.word + '".';
      status.className = 'status win';
    } else {
      guessRow++;
      currentGuess = [];
      if (guessRow >= maxGuesses) {
        finished = true;
        status.textContent = 'Out of guesses. The word was "' + DATA.word + '".';
        status.className = 'status lose';
      }
    }
  }

  window.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') submitGuess();
    if (e.key === 'Backspace') backspace();
  });
</script>
</body>
</html>`;
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
