// HCE (broad transcription) phoneme data, sourced from HCE_Wordle_Phoneme_Corpus.docx
// Each keyboard entry maps an IPA symbol to a plain-English label and example word.
// This is a fixed, hard-coded corpus for Assessment 1. A database-backed, teacher-editable
// version is planned for Assessment 2+.

export const PHONEME_KEYBOARD = [
  { ipa: "p", label: "P", example: "pat" },
  { ipa: "t", label: "T", example: "top" },
  { ipa: "k", label: "K", example: "cat" },
  { ipa: "b", label: "B", example: "bed" },
  { ipa: "d", label: "D", example: "dog" },
  { ipa: "ɡ", label: "G", example: "gum" },
  { ipa: "n", label: "N", example: "net" },
  { ipa: "m", label: "M", example: "map" },
  { ipa: "ŋ", label: "NG", example: "ring" },
  { ipa: "f", label: "F", example: "fan" },
  { ipa: "s", label: "S", example: "sun" },
  { ipa: "θ", label: "TH", example: "thin" },
  { ipa: "ʃ", label: "SH", example: "ship" },
  { ipa: "v", label: "V", example: "van" },
  { ipa: "z", label: "Z", example: "zip" },
  { ipa: "ð", label: "TH", example: "then" },
  { ipa: "ʒ", label: "ZH", example: "measure" },
  { ipa: "l", label: "L", example: "log" },
  { ipa: "ɹ", label: "R", example: "ring" },
  { ipa: "w", label: "W", example: "win" },
  { ipa: "j", label: "Y", example: "yes" },
  { ipa: "h", label: "H", example: "hat" },
  { ipa: "tʃ", label: "CH", example: "chin" },
  { ipa: "dʒ", label: "J", example: "jam" },
  { ipa: "iː", label: "EE", example: "see" },
  { ipa: "ɪ", label: "I", example: "bid" },
  { ipa: "e", label: "E", example: "bed" },
  { ipa: "eː", label: "AIR", example: "hair" },
  { ipa: "æ", label: "A", example: "bad" },
  { ipa: "ɐ", label: "U", example: "bud" },
  { ipa: "ɐː", label: "AR", example: "bark" },
  { ipa: "ɜː", label: "ER", example: "bird" },
  { ipa: "ʉː", label: "OO", example: "boot" },
  { ipa: "ɔ", label: "O", example: "log" },
  { ipa: "oː", label: "OR", example: "fork" },
  { ipa: "ʊ", label: "OO", example: "book" },
  { ipa: "æɪ", label: "AI", example: "bait" },
  { ipa: "ɑe", label: "IGH", example: "bike" },
  { ipa: "oɪ", label: "OY", example: "boil" },
  { ipa: "əʉ", label: "OW", example: "boat" },
  { ipa: "æɔ", label: "OU", example: "cloud" },
  { ipa: "ɪə", label: "EAR", example: "beard" },
  { ipa: "ə", label: "UH", example: "sofa" },
];

// quick lookup: ipa symbol -> { label, example }
export const PHONEME_MAP = Object.fromEntries(
  PHONEME_KEYBOARD.map((p) => [p.ipa, { label: p.label, example: p.example }])
);

// Word bank grouped by phoneme-count difficulty, [word, [phoneme units]]
export const WORD_BANK = {
  3: [
    ["bed", ["b", "e", "d"]],
    ["bid", ["b", "ɪ", "d"]],
    ["bad", ["b", "æ", "d"]],
    ["bud", ["b", "ɐ", "d"]],
    ["bird", ["b", "ɜː", "d"]],
    ["bark", ["b", "ɐː", "k"]],
    ["book", ["b", "ʊ", "k"]],
    ["boot", ["b", "ʉː", "t"]],
    ["boat", ["b", "əʉ", "t"]],
    ["bike", ["b", "ɑe", "k"]],
    ["bait", ["b", "æɪ", "t"]],
    ["boil", ["b", "oɪ", "l"]],
    ["beard", ["b", "ɪə", "d"]],
    ["choice", ["tʃ", "oɪ", "s"]],
    ["thin", ["θ", "ɪ", "n"]],
    ["then", ["ð", "e", "n"]],
    ["ship", ["ʃ", "ɪ", "p"]],
    ["chin", ["tʃ", "ɪ", "n"]],
    ["jam", ["dʒ", "æ", "m"]],
    ["yes", ["j", "e", "s"]],
    ["win", ["w", "ɪ", "n"]],
    ["ring", ["ɹ", "ɪ", "ŋ"]],
    ["log", ["l", "ɔ", "ɡ"]],
    ["fan", ["f", "æ", "n"]],
    ["van", ["v", "æ", "n"]],
    ["sun", ["s", "ɐ", "n"]],
    ["zip", ["z", "ɪ", "p"]],
    ["gum", ["ɡ", "ɐ", "m"]],
    ["hat", ["h", "æ", "t"]],
    ["fork", ["f", "oː", "k"]],
  ],
  4: [
    ["stop", ["s", "t", "ɔ", "p"]],
    ["frog", ["f", "ɹ", "ɔ", "ɡ"]],
    ["clap", ["k", "l", "æ", "p"]],
    ["slip", ["s", "l", "ɪ", "p"]],
    ["drum", ["d", "ɹ", "ɐ", "m"]],
    ["grin", ["ɡ", "ɹ", "ɪ", "n"]],
    ["train", ["t", "ɹ", "æɪ", "n"]],
    ["cloud", ["k", "l", "æɔ", "d"]],
    ["snake", ["s", "n", "æɪ", "k"]],
    ["smile", ["s", "m", "ɑe", "l"]],
    ["milk", ["m", "ɪ", "l", "k"]],
    ["hand", ["h", "æ", "n", "d"]],
    ["tent", ["t", "e", "n", "t"]],
    ["jump", ["dʒ", "ɐ", "m", "p"]],
    ["lamp", ["l", "æ", "m", "p"]],
    ["bank", ["b", "æ", "ŋ", "k"]],
    ["frame", ["f", "ɹ", "æɪ", "m"]],
    ["cold", ["k", "əʉ", "l", "d"]],
    ["wind", ["w", "ɪ", "n", "d"]],
    ["soft", ["s", "ɔ", "f", "t"]],
    ["gift", ["ɡ", "ɪ", "f", "t"]],
    ["desk", ["d", "e", "s", "k"]],
    ["left", ["l", "e", "f", "t"]],
    ["pond", ["p", "ɔ", "n", "d"]],
    ["golf", ["ɡ", "ɔ", "l", "f"]],
    ["silk", ["s", "ɪ", "l", "k"]],
    ["great", ["ɡ", "ɹ", "æɪ", "t"]],
    ["crab", ["k", "ɹ", "æ", "b"]],
    ["plug", ["p", "l", "ɐ", "ɡ"]],
    ["quiz", ["k", "w", "ɪ", "z"]],
  ],
  5: [
    ["stamp", ["s", "t", "æ", "m", "p"]],
    ["plant", ["p", "l", "æ", "n", "t"]],
    ["blank", ["b", "l", "æ", "ŋ", "k"]],
    ["grand", ["ɡ", "ɹ", "æ", "n", "d"]],
    ["clamp", ["k", "l", "æ", "m", "p"]],
    ["twist", ["t", "w", "ɪ", "s", "t"]],
    ["trust", ["t", "ɹ", "ɐ", "s", "t"]],
    ["drink", ["d", "ɹ", "ɪ", "ŋ", "k"]],
    ["brisk", ["b", "ɹ", "ɪ", "s", "k"]],
    ["shrimp", ["ʃ", "ɹ", "ɪ", "m", "p"]],
    ["scrap", ["s", "k", "ɹ", "æ", "p"]],
    ["scribe", ["s", "k", "ɹ", "ɑe", "b"]],
    ["scream", ["s", "k", "ɹ", "iː", "m"]],
    ["splash", ["s", "p", "l", "æ", "ʃ"]],
    ["spring", ["s", "p", "ɹ", "ɪ", "ŋ"]],
    ["strap", ["s", "t", "ɹ", "æ", "p"]],
    ["street", ["s", "t", "ɹ", "iː", "t"]],
    ["scrub", ["s", "k", "ɹ", "ɐ", "b"]],
    ["flask", ["f", "l", "ɐː", "s", "k"]],
    ["clasp", ["k", "l", "ɐː", "s", "p"]],
    ["cleft", ["k", "l", "e", "f", "t"]],
    ["glint", ["ɡ", "l", "ɪ", "n", "t"]],
    ["blend", ["b", "l", "e", "n", "d"]],
    ["strain", ["s", "t", "ɹ", "æɪ", "n"]],
    ["thrust", ["θ", "ɹ", "ɐ", "s", "t"]],
    ["sprawl", ["s", "p", "ɹ", "oː", "l"]],
    ["scrawl", ["s", "k", "ɹ", "oː", "l"]],
    ["sprig", ["s", "p", "ɹ", "ɪ", "ɡ"]],
    ["sprout", ["s", "p", "ɹ", "æɔ", "t"]],
    ["smoked", ["s", "m", "əʉ", "k", "t"]],
  ],
};

// Fixed default word search list (~5 words) for Assessment 1, as required by the brief.
export const WORD_SEARCH_DEFAULT = [
  ["chin", ["tʃ", "ɪ", "n"]],
  ["bait", ["b", "æɪ", "t"]],
  ["jam", ["dʒ", "æ", "m"]],
  ["ring", ["ɹ", "ɪ", "ŋ"]],
  ["boot", ["b", "ʉː", "t"]],
];
